const articleDataStructure = {
  austria: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  belgium: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  bulgaria: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  croatia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  cyprus: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  czechia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  denmark: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  estonia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  finland: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  france: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  germany: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  greece: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  hungary: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  ireland: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  italy: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  latvia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  lithuania: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  luxembourg: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  netherlands: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  poland: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  portugal: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  romania: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  slovakia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  slovenia: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  spain: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  sweden: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  uk: {
    general: [],
    business: [],
    technology: [],
    entertainment: [],
  },
  customSearch: [],
}

export default articleDataStructure
