<!-- eslint-disable vue/attribute-hyphenation, max-lines -->
<template>
  <defs>
    <pattern
      id="eu-blue-fill"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
    >
      <rect
        fill="#FADD44"
        x="0"
        y="0"
        width="1"
        height="1"
      />
    </pattern>
    <pattern
      id="poland"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2"
        height=".5"
        x="-.1"
        fill="#fff"
      />
      <rect
        width="2"
        height=".5"
        fill="#dc143c"
        y=".5"
      />
    </pattern>
    <pattern
      id="germany"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        id="black_stripe"
        width="4"
        height="1"
        y="-.3"
        x="-1"
        fill="#000"
      />
      <rect
        id="red_stripe"
        width="1"
        height=".8"
        y=".3"
        x="0"
        fill="#D00"
      />
      <rect
        id="gold_stripe"
        width="1"
        height="1"
        y=".8"
        x="0"
        fill="#FFCE00"
      />
    </pattern>
    <pattern
      id="france"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width=".33"
        height="1"
        x="0"
        fill="#ED2939"
      />
      <rect
        width=".33"
        height="1"
        x=".33"
        fill="#fff"
      />
      <rect
        width=".34"
        height="1"
        x=".66"
        fill="#002395"
      />
    </pattern>
    <pattern
      id="spain"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2"
        height="1"
        x="-.5"
        fill="#c60b1e"
      />
      <rect
        width="2"
        height=".5"
        x="-.5"
        fill="#ffc400"
        y=".25"
      />
    </pattern>
    <pattern
      id="portugal"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="9"
      height="6"
    >
      <image
        xlink:href="https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"
        x="-.4"
        y="0"
        width="2"
        height="1"
      />
    </pattern>
    <pattern
      id="italy"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width=".33"
        height="2"
        x="0"
        y="-.2"
        fill="#008C45"
      />
      <rect
        width=".33"
        height="2"
        x=".33"
        y="-.2"
        fill="#fff"
      />
      <rect
        width=".34"
        height="2"
        x=".66"
        fill="#CD212A"
      />
    </pattern>
    <pattern
      id="sicily"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      view-box="0 0 1 1"
    >
      <rect
        width="3"
        height="2"
        x="-.5"
        fill="#F4F5F0"
      />
      <rect
        width="1"
        height="2"
        x=".8"
        fill="#CD212A"
      />
    </pattern>
    <pattern
      id="sweden"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height="3"
        y="-1"
        fill="#236AA6"
      />
      <rect
        width=".25"
        height="3"
        y="-1"
        x=".2"
        fill="#F9CC16"
      />
      <rect
        width="1"
        height=".25"
        y=".8"
        x="0"
        fill="#F9CC16"
      />
    </pattern>
    <pattern
      id="finland"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height="3"
        y="-1"
        fill="white"
      />
      <rect
        width=".3"
        height="3"
        y="-1"
        x=".3"
        fill="#002f6c"
      />
      <rect
        width="1"
        height=".3"
        y=".9"
        x="0"
        fill="#002f6c"
      />
    </pattern>
    <pattern
      id="denmark"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height="3"
        y="-1"
        fill="#C00025"
      />
      <rect
        width=".2"
        height="3"
        y="-1"
        x=".3"
        fill="#F4F5F0"
      />
      <rect
        width="1"
        height=".2"
        y=".4"
        x="0"
        fill="#F4F5F0"
      />
    </pattern>
    <pattern
      id="belgium"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width=".43"
        height="1"
        x="-.1"
        fill="black"
      />
      <rect
        width=".33"
        height="1"
        x=".33"
        fill="#FDDA24"
      />
      <rect
        width=".33"
        height="1"
        x=".66"
        fill="#EF3340"
      />
    </pattern>
    <pattern
      id="netherlands"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height=".43"
        y="-.1"
        fill="#bf3922"
      />
      <rect
        width="1"
        height=".33"
        y=".33"
        fill="#FFFFFF"
      />
      <rect
        width="1"
        height=".45"
        y=".6"
        fill="#193153"
      />
    </pattern>
    <pattern
      id="luxembourg"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="2"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height=".33"
        y="0"
        x="-.5"
        fill="#F6343F"
      />
      <rect
        width="1"
        height=".33"
        y=".33"
        x="-.5"
        fill="#FFFFFF"
      />
      <rect
        width="1"
        height=".33"
        y=".66"
        x="-.5"
        fill="#00A2E1"
      />
    </pattern>
    <pattern
      id="ireland"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        height="1"
        width=".43"
        x="-.1"
        fill="#169B62"
      />
      <rect
        height="1"
        width=".33"
        x=".33"
        fill="#FFFFFF"
      />
      <rect
        height="1"
        width=".43"
        x=".66"
        fill="#FF883E"
      />
    </pattern>
    <pattern
      id="uk"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="9"
      height="6"
    >
      <image
        xlink:href="https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg"
        x="-.4"
        y="0"
        width="2"
        height="1"
      />
    </pattern>
    <pattern
      id="northernIreland"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2"
        height=".4"
        x="-.5"
        y="0"
        fill="white"
      />
      <rect
        width="2"
        height=".66"
        x="-.5"
        y=".4"
        fill="#CD212A"
      />
    </pattern>
    <pattern
      id="czechia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        height=".5"
        width="2"
        x="-.5"
        y=".5"
        fill="#dc143c"
      />
      <rect
        height=".5"
        width="2"
        x="-.5"
        fill="white"
      />
      <polygon
        points="-.5 1, -.5 0, .3 .5"
        fill="#11457E"
      />
    </pattern>
    <pattern
      id="austria"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        height="2"
        width="3"
        x="-1"
        y="0"
        fill="#dc143c"
      />
      <rect
        height=".35"
        width="3"
        x="-1"
        y=".35"
        fill="white"
      />
    </pattern>
    <pattern
      id="hungary"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".43"
        y="-.1"
        x="-.6"
        fill="#CD2A3E"
      />
      <rect
        width="2.2"
        height=".33"
        y=".33"
        x="-.6"
        fill="#FFFFFF"
      />
      <rect
        width="2.2"
        height=".45"
        y=".66"
        x="-.6"
        fill="#436F4D"
      />
    </pattern>
    <pattern
      id="slovakia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".43"
        y="-.1"
        x="-.6"
        fill="#FFF"
      />
      <rect
        width="2.2"
        height=".33"
        y=".33"
        x="-.6"
        fill="#0b4ea2"
      />
      <rect
        width="2.2"
        height=".45"
        y=".66"
        x="-.6"
        fill="#ee1c25"
      />
    </pattern>
    <pattern
      id="romania"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        height="1"
        width=".5"
        x="-.2"
        fill="#002B7F"
      />
      <rect
        height="1"
        width=".5"
        x=".3"
        fill="#FCD116"
      />
      <rect
        height="1"
        width=".5"
        x=".7"
        fill="#CE1126"
      />
    </pattern>
    <pattern
      id="bulgaria"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".43"
        y="-.1"
        x="-.6"
        fill="#FFF"
      />
      <rect
        width="2.2"
        height=".33"
        y=".33"
        x="-.6"
        fill="#00966E"
      />
      <rect
        width="2.2"
        height=".45"
        y=".66"
        x="-.6"
        fill="#D62612"
      />
    </pattern>
    <pattern
      id="cyprus"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="2"
      height="6"
    >
      <image
        xlink:href="https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg"
        x="-.2"
        y="0"
        width="1.2"
        height="1.2"
      />
    </pattern>
    <pattern
      id="slovenia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".43"
        y="-.1"
        x="-.6"
        fill="#FFF"
      />
      <rect
        width="2.2"
        height=".33"
        y=".33"
        x="-.6"
        fill="#005DA4"
      />
      <rect
        width="2.2"
        height=".45"
        y=".66"
        x="-.6"
        fill="#ED1C24"
      />
    </pattern>
    <pattern
      id="croatia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".43"
        y="-.1"
        x="-.6"
        fill="#ff0000"
      />
      <rect
        width="2.2"
        height=".33"
        y=".33"
        x="-.6"
        fill="#ffffff"
      />
      <rect
        width="2.2"
        height=".45"
        y=".66"
        x="-.6"
        fill="#171796"
      />
    </pattern>
    <pattern
      id="greece1"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="9"
      height="6"
    >
      <image
        xlink:href="https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"
        x="-.1"
        y="-.3"
        width="2"
        height="2"
      />
    </pattern>
    <pattern
      id="greece2"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="1"
        height=".5"
        y="0"
        fill="#0D5EAF"
      />
      <rect
        width="1"
        height=".5"
        y=".5"
        fill="#FFF"
      />
    </pattern>
    <pattern
      id="lithuania"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".33"
        y="0"
        x="-.6"
        fill="#FDB913"
      />
      <rect
        width="2.2"
        height=".4"
        y=".3"
        x="-.6"
        fill="#006A44"
      />
      <rect
        width="2.2"
        height=".33"
        y=".66"
        x="-.6"
        fill="#C1272D"
      />
    </pattern>
    <pattern
      id="latvia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        height="2"
        width="3"
        x="-1"
        y="0"
        fill="#9E1B34"
      />
      <rect
        height=".2"
        width="3"
        x="-1"
        y=".4"
        fill="white"
      />
    </pattern>
    <pattern
      id="estonia"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2.2"
        height=".33"
        y="0"
        x="-.6"
        fill="#0072CE"
      />
      <rect
        width="2.2"
        height=".4"
        y=".3"
        x="-.6"
        fill="#000000"
      />
      <rect
        width="2.2"
        height=".33"
        y=".66"
        x="-.6"
        fill="#FFFFFF"
      />
    </pattern>
    <pattern
      id="estonia2"
      patternUnits="objectBoundingBox"
      patternContentUnits="objectBoundingBox"
      x="0"
      y="0"
      width="1"
      height="1"
      viewBox="0 0 1 1"
    >
      <rect
        width="2"
        height=".2"
        y="0"
        x="-.6"
        fill="#000000"
      />
      <rect
        width="2"
        height=".8"
        y=".2"
        x="-.6"
        fill="#FFFFFF"
      />
    </pattern>
  </defs>
</template>
